# Generated by Django 3.2.8 on 2021-11-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211103_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ex_price',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(max_length=10),
        ),
    ]
